add Content Panels for Musicvideos in SearchEngine
jurialmunkey/skin.arctic.zephyr.2 pull request #13
Opened 2019-04-01 08:52 UTC by marduklev

- find titles by searchstring
- find artist by search string

2019-04-02 08:11 UTC, jurialmunkey requested changes
Looks good! Can you just localize the "by" on line 269 and then I will merge. Thanks 😃

2019-04-02 08:11 UTC, jurialmunkey commented on 1080i/Custom_1138_Search.xml
> +                    <param name="label" value="$INFO[Container(5016).NumItems,$LOCALIZE[20389] by (,)]" />
Can you localize the "by" on this line?

2019-04-11 22:16 UTC, jurialmunkey commented
Hi. Just wondering if you were going to make the above requested change?

2019-04-13 11:48 UTC, marduklev commented
Sorry for late response, will check next monday.
I need also to check the artwork image

2019-04-14 23:10 UTC, jurialmunkey commented
Not a problem. No need to rush - was just making sure you hadn't missed my comments.

2019-04-15 08:24 UTC, marduklev commented
ok, unsure if it'll cause wrong it'll cause "grammar issues" if it'll use that 

 - $INFO[Skin.String(SearchTerm),$LOCALIZE[20391] - $LOCALIZE[133] $LOCALIZE[21400]  &quot; , &quot; ] $INFO[Container(5001).NumItems, (,)]

music videos - artist contains "searchstring" (numitems)

or if i should do pr , with a predefined label in language strings(.po)
 - $INFO[Skin.String(SearchTerm),$LOCALIZE[20389] $LOCALIZE[31432] &quot;[CAPITALIZE],[/CAPITALIZE]&quot;]$INFO[Container(5013).NumItems, (,)]
 
 = Music viedeos - "by Artist named" 'Searchstring' 

 - #: /1080i/Custom_1138_Search.xml
 - msgctxt "#31432"
 - msgid "By Artist Named"
 - msgstr ""

2019-04-16 23:39 UTC, jurialmunkey commented
Grammatical issues might be a problem, so I've been trying to keep it as simple as possible. 
e.g. For Albums by Artist I used the format: "Albums by 'Artist'"
The "Albums by" is localized as one string.

Maybe this would be best:
Music Videos by 'SearchString'
"Music Videos by" as one localized string.

2019-04-18 07:43 UTC, marduklev commented
- i think its done, at least , you should just check if you really want ListItem.Icon, instead of an variable for fanart

# e.g.
```
<value condition="!String.IsEmpty(ListItem.Art(artist.landscape))">$INFO[ListItem.Art(artist.landscape)]</value>
	<value condition="!String.IsEmpty(ListItem.Art(albumartist.landscape))">$INFO[ListItem.Art(albumartist.landscape)]</value>
	<value condition="!String.IsEmpty(ListItem.Art(landscape))">$INFO[ListItem.Art(landscape)]</value>
	<value condition="!String.IsEmpty(ListItem.Art(artist.fanart))">$INFO[ListItem.Art(artist.fanart)]</value>
	<value condition="!String.IsEmpty(ListItem.Art(albumartist.landscape))">$INFO[ListItem.Art(albumartist.fanart)]</value>
	<value condition="!String.IsEmpty(ListItem.Art(fanart))">$INFO[ListItem.Art(fanart)]</value>
	<value>$INFO[ListItem.Icon]</value>
```

2019-04-19 23:31 UTC, merged

2019-04-19 23:34 UTC, jurialmunkey commented
I made a few small changes, but everything has been merged.
Changed artwork to square as musicvideos default scraper scrapes album covers as ListItem.Icon and there doesn't seem to be anyway to get the actual video thumbnail (which is what I would actually prefer).
Changed the "by artist named" string to be one string "Music Videos by Artist Named" rather than two combined.