:art: - Add Material Design color palette
jurialmunkey/skin.arctic.zephyr.2 pull request #81
Opened 2019-07-18 16:16 UTC by drinfernoo

2019-07-20 03:55 UTC, jurialmunkey requested changes
Looks good. Can you just make the requested changes on the lines that I've commented. Mostly just revert the padding back to its original values and change the itemlayout width/height to 100 so that you get more items fitting on the page.

Also, in `<control type="panel" id="3110">` change the bottom tag so that it is `<bottom>20</bottom>`

These changes will make sure that all items fit properly on the screen with the correct padding from sides/bottom of dialog.

Also, thanks for the PR. Really appreciate having improvements PR'd so I can just merge them! 😁

2019-07-20 03:55 UTC, jurialmunkey commented on 1080i/script-skin_helper_service-ColorPicker.xml
> +                <itemlayout width="128" height="128">
Can you change this to `<itemlayout width="100" height="100">`

2019-07-20 03:55 UTC, jurialmunkey commented on 1080i/script-skin_helper_service-ColorPicker.xml
> +                        <bottom>8</bottom>
Can you revert the right/bottom padding back to 10

2019-07-20 03:55 UTC, jurialmunkey commented on 1080i/script-skin_helper_service-ColorPicker.xml
> +                        <bottom>16</bottom>
Same here. Can you revert the padding top/left pad to 10 and right/bottom pad to 20

2019-07-20 03:55 UTC, jurialmunkey commented on 1080i/script-skin_helper_service-ColorPicker.xml
> +                <focusedlayout width="128" height="128">
Same here. Can you change to `<focusedlayout width="100" height="100">`

2019-07-20 03:55 UTC, jurialmunkey commented on 1080i/script-skin_helper_service-ColorPicker.xml
> +                        <bottom>8</bottom>
Same here. Can you revert the right/bottom pad to 10

2019-07-20 15:37 UTC, drinfernoo commented
I'll definitely make the changes! I wondered if maybe a toggle for "tile size" might be useful?

2019-07-20 17:35 UTC, drinfernoo commented
I went ahead and fixed the padding for you 👍 I only changed it in the first place because Material Design uses baselines at 8-unit intervals... So I felt like it would be appropriate 😆

2019-07-21 06:39 UTC, merged

2019-07-21 06:39 UTC, jurialmunkey commented
Cheers! Merged. 😁

2019-07-21 06:53 UTC, drinfernoo commented
As an aside, do you think configurable cell layouts would be desirable or overkill?

2019-07-21 07:09 UTC, jurialmunkey commented
Maybe if it was automatic and linked to which palette was selected, but it's probably overkill really.